name: Android OPS

on:
  push:
    branches:
      - 'develop'

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradle wrapper executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --stacktrace --no-daemon --console plain build
    - name: Save lint results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: lint-result
        path: app/build/reports/
        
        
  apk:
    name: Generate APK
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
   
  master:
    name: Create PR
    needs: apk
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: pull-request
          uses: repo-sync/pull-request@v2
          with:
             destination_branch: "main"
             github_token: ${{ secrets.GITHUB_TOKEN }}
